---
- name: "Install kubelet (1/8)"
  apt:
    name: kubelet
    state: present

- name: "Install kubectl (2/8)"
  apt:
    name: kubectl
    state: present

- name: "Install kubeadm (3/8)"
  apt:
    name: kubeadm
    state: present


- name: "Adjust swapiness for k8s (4/8)"
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'vm.swappiness = 0'
    state: present
    create: yes

- name: "Configure vm overcommit_memory (5/8)"
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'vm.overcommit_memory = 1'
    state: present
    create: yes

- name: "Add netbridge config ip4 (6/8)"
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.bridge.bridge-nf-call-iptables = 1'
    state: present
    create: yes

- name: "Increase net ipv4 tcp_max_syn_backlog (7/8)"
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.ipv4.tcp_max_syn_backlog=2621440'
    state: present
    create: yes


- name: "Start and enable kubelet (8/8)"
  systemd:
    state: started
    daemon_reload: yes
    name: kubelet
    enabled: yes