---
- import_playbook: k8s/k8s-repository.yaml
- import_playbook: k8s/disable-swap.yaml
- import_playbook: k8s/install-cri.yaml
- import_playbook: k8s/kubeadm-prep.yaml
- import_playbook: k8s/kubeadm-init-master.yaml
- import_playbook: k8s/install-cilium.yaml
- import_playbook: k8s/kubeadm-join-masters.yaml
- import_playbook: k8s/kubeadm-join-workers.yaml